basePath: http://localhost:7000

spring:
  datasource:
    url: jdbc:mysql://172.100.2.101:3306/finix
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

debug: true

file:
  location: /Users/ndung/Workspace/finix-backend/images

publicKey: /Users/ndung/Workspace/finix-backend/public_key.der

