spring:
  datasource:
    url: jdbc:mysql://192.168.46.107:3306/digital_xylarium
    username: dx
    password: dx1234
    driver-class-name: com.mysql.jdbc.Driver

debug: true

file:
  location: /dataset/

publicKey: /home/lmanik/dx/public_key.der

